### ISSUE TITLE
Uppercase characters in tenant name

### ISSUE THREAD

**Issue by micoq** [floragunncom/search-guard-module-kibana-multitenancy#11]
Elasticsearch doesn't allow to create an index with uppercase characters in its name so you can't create tenants with uppercase characters:

In `sg_roles.yml`, I add a tenant `TOTO`:
```
sg_all_access:
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    TOTO: RW
```

In Kibana, I can switch to this tenant but I can't access the "Discover","Management"... tabs (only Timelion works). If you analyze the browser request, you can notice a 404 error on
`/es_admin/kibana/index-pattern/_search?stored_fields=`
with this response:
`type	"index_not_found_exception"`

On Elasticsearch you have a error like this:
`Invalid index name [kibana_xxxxx_TOTO], must be lowercase`

The solution would be to encode the tenant name in the index name (or to denied uppercase characters ?).

SearchGuard version : 5.3.0-12
